//ip-172-18-62-86
function contentAd623317() {
var line = "";
line += '<div id="ac_623317">';
line += '<div class="ac_header_title">You Might Also Like</div>';
line += '<div class="ac_adbox">';
line += '<div class="ac_adbox_inner">';
line += '<!-- start ads -->';
line += '<div class="ac_container">';
line += '<a class="ac_image_link" rel="nofollow" target="_blank" href="https://api.content-ad.net/Lib/TrackOutboundClick.aspx?hid=1&wid=623317&uid=2277711&did=323021&sid=&type=3&s=ip-172-18-62-86&pid=0&c=KE&d=&aid=8DB38BA3-CF48-42E6-8AFD-457A1EFC7626&ik=2019041600_cdbb18d9f3abd3736a24050d75745bf5&it=2019-04-16+00%3A40%3A01.955&hai=32127&ti=P03&ck=8250c5097849d858a4e074c49b79c175&clientId=&clientId2=&v=&wdi=underpick%3A1%2Cpj1on%2C&adi=&t=false&ct=widget&dl=false&odi=323021&redirectUrl=5g0K9kapAEFigdi8ufzTLxXDZK6u3y%2FWiBqdK%2BkTz4b7csUjQ%2BLtWgkrjzQBRzFnxa1ZDD9yDUAAzPsJDQ9rY6Md9CUeiG3X%2BpfBF3Xh3Kd4nJXyFUrI9LNv6tpCcIApjYOfziSR%2Fu%2B52TvULFkmoeUxe1ea3bt7mTSpMyNKDxwGUvME6c6weyvHDAX9MMkw" onclick="javascript:widget623317.clk(this)">';
line += '<img height="250" width="300" src="https://d3dytsf4vrjn5x.cloudfront.net/2724/300x250/69d243a4f81bca72a29828f67d7d7808.jpg" alt="How to Monitor Your Kid’s iPhone  Without Taking It Away" class="ac_image" title="How to Monitor Your Kid’s iPhone  Without Taking It Away" />';
line += '</a>';
line += '<div class="ac_title_wrapper">';
line += '<a class="ac_title" rel="nofollow" target="_blank" href="https://api.content-ad.net/Lib/TrackOutboundClick.aspx?hid=1&wid=623317&uid=2277711&did=323021&sid=&type=3&s=ip-172-18-62-86&pid=0&c=KE&d=&aid=8DB38BA3-CF48-42E6-8AFD-457A1EFC7626&ik=2019041600_cdbb18d9f3abd3736a24050d75745bf5&it=2019-04-16+00%3A40%3A01.955&hai=32127&ti=P03&ck=8250c5097849d858a4e074c49b79c175&clientId=&clientId2=&v=&wdi=underpick%3A1%2Cpj1on%2C&adi=&t=false&ct=widget&dl=false&odi=323021&redirectUrl=5g0K9kapAEFigdi8ufzTLxXDZK6u3y%2FWiBqdK%2BkTz4b7csUjQ%2BLtWgkrjzQBRzFnxa1ZDD9yDUAAzPsJDQ9rY6Md9CUeiG3X%2BpfBF3Xh3Kd4nJXyFUrI9LNv6tpCcIApjYOfziSR%2Fu%2B52TvULFkmoeUxe1ea3bt7mTSpMyNKDxwGUvME6c6weyvHDAX9MMkw" onclick="javascript:widget623317.clk(this)">';
line += 'How to Monitor Your Kid’s iPhone  Without Taking It Away';
line += '</a>';
line += '</div>';
line += '</div>';
line += '<!-- end ads -->';
line += '<img class="ac_pixel" src="https://api.content-ad.net/pixel.gif?s=ip-172-18-62-86&ip=197.232.29.98&wid=623317&cb=1555400401955&c=KE&d=&ik=2019041600_cdbb18d9f3abd3736a24050d75745bf5" height="1" width="1" />';
line += '<img class="ac_pixel" src="https://api.content-ad.net/px.gif" height="1" width="1" />';
line += '</div>';
line += '<div style="clear:both;"></div>';
line += '<div class="ac_credit">';
line += '<span class="ac_disclaimer">Sponsored Content</span>';
line += '<a href="https://www.content.ad/AboutUs?utm_medium=modal&utm_source=widget_623317&widgetId=623317&d=Desktop&u=https%3A%2F%2Fdiscordbots.org%2Fbot%2F405074538578313216" target="_blank" rel="nofollow">?</a>';
line += '</div>';
line += '<div class="ac_modal_shading"></div>';
line += '<div class="ac_credit_copy">';
line += '<div class="ac_credit_logo">';
line += '<img src="https://d32oduq093hvot.cloudfront.net/icons/c_ad_logo.png" />';
line += '</div>';
line += '<p>These content links are provided by <a href="https://www.content.ad/?utm_medium=modal&utm_source=widget_623317">Content.ad</a>. Both Content.ad and the web site upon which the links are displayed may receive compensation when readers click on these links. Some of the content you are redirected to may be sponsored content. View our privacy policy <a href="https://d32oduq093hvot.cloudfront.net/site/privacy_v1.html?utm_medium=modal&utm_source=widget_623317" target="_blank" rel="nofollow">here</a>.</p>';
line += '<p>To learn how you can use Content.ad to drive visitors to your content or add this service to your site, please contact us at <a href="mailto:info@content.ad?subject=Contact%20from%20Widget%20623317&body=In%20order%20for%20us%20to%20better%20assist%20you%2C%20we%27ve%20added%20the%20following%20details%20to%20track%20where%20you%20saw%20our%20ads.%20Please%20do%20not%20remove%20or%20change%20this%20information.%0A%0APage%20URL:%20https%3A%2F%2Fdiscordbots.org%2Fbot%2F405074538578313216%0AWidget%20ID:%20623317%0ADevice%20Type:%20Desktop%0A%0A%3d%3d%3dAdd%20your%20message%20below%20this%20line%3d%3d%3d%0A" rel="nofollow">info@content.ad</a>.</p>';
line += '<div class="family-friendly">';
line += '<p><strong>Family-Friendly Content</strong></p>';
line += '<p><label><input type="checkbox" id="familyFriendlyContent" onclick="familyFriendlyHandler(623317, this)"  /> Only recommend family-friendly content</label></p>';
line += '<p>Website owners select the type of content that appears in our units. However, if you would like to ensure that Content.ad always displays family-friendly content on this device, regardless of what site you are on, check the option below. <a href="https://d32oduq093hvot.cloudfront.net/site/family_friendly_v1.html?utm_medium=modal&utm_source=widget_623317" target="_blank">Learn More</a></p>';
line += '</div>';
line += '</div>';
line += '</div>';
line += '<div style="clear:both;"></div>';
line += '</div>';
line += '<style type="text/css" id="ac_623317_css">';
line += '/* Banner - 320x50 */';
line += '#ac_623317, #ac_623317 div, #ac_623317 span, #ac_623317 a, #ac_623317 img {';
line += 'margin: 0;';
line += 'padding: 0;';
line += 'border: 0;';
line += 'font-size: 14px;';
line += 'font: normal 14px/1.428em Arial, Helvetica, sans-serif;';
line += 'vertical-align: baseline;';
line += '}';
line += '#ac_623317 {';
line += 'clear: both;';
line += 'display: block;';
line += 'text-align: left;';
line += 'height: 50px;';
line += 'width: 320px;';
line += 'margin: 0;';
line += 'position: relative;';
line += 'font-size: 16px;';
line += 'text-align: left;';
line += 'line-height: 1.428em;';
line += 'overflow: hidden;';
line += 'background: #fff;';
line += '}';
line += '#ac_623317 .ac_header_title {';
line += 'display: none;';
line += '}';
line += '#ac_623317 .ac_adbox {';
line += 'width:100%;';
line += 'height: 100%;';
line += 'position:relative;';
line += 'display:block;';
line += 'clear:both;';
line += 'text-align:left;';
line += 'text-decoration:none;';
line += '}';
line += '#ac_623317 .ac_image {';
line += 'width:85px;';
line += 'height:auto;';
line += 'border:none !important;';
line += 'margin:-11px 0 0 !important;';
line += 'display:block;';
line += 'padding: 0 !important;';
line += 'max-width:100%;';
line += '}';
line += '#ac_623317 .ac_container {';
line += 'display:inline-block;';
line += '*display:inline;';
line += 'zoom:1;';
line += 'vertical-align:top;';
line += '}';
line += '#ac_623317 .ac_container:hover .ac_title_wrapper .ac_title {';
line += 'text-decoration:underline;';
line += '}';
line += '#ac_623317 .ac_container a {';
line += 'display:block;';
line += 'direction:ltr;';
line += 'text-align:left;';
line += 'text-decoration:none;';
line += '}';
line += '#ac_623317 .ac_title_wrapper {';
line += 'display: inline-block;';
line += 'width:200px;';
line += 'padding: 2px 0 0 8px;';
line += 'vertical-align: top;';
line += '}';
line += '#ac_623317 .ac_title_wrapper .ac_title {';
line += 'margin: 0;';
line += 'border: none;';
line += 'direction: ltr;';
line += 'text-align: left;';
line += 'vertical-align: middle;';
line += 'word-wrap: break-word;';
line += 'width: 100%;';
line += 'padding: 0;';
line += 'font-size: 0.93em;';
line += 'line-height: 1.25em;';
line += 'color: #0000ee;';
line += 'overflow: hidden;';
line += '}';
line += '#ac_623317 .ac_referrer {';
line += 'position: absolute;';
line += 'font-size:10px;';
line += 'font-weight:normal;';
line += 'font-style:italic;';
line += 'color:#888;';
line += 'word-wrap:break-word;';
line += 'background: #FFF;';
line += 'bottom: 0;';
line += 'height: 16px;';
line += 'width: 105px;';
line += 'white-space: nowrap;';
line += 'overflow: hidden;';
line += 'text-overflow: ellipsis;';
line += '}';
line += '#ac_623317 a.ac_image_link {';
line += 'display:inline-block;';
line += '*display:inline;';
line += 'zoom:1;';
line += 'margin-right:0;';
line += 'position:relative;';
line += 'overflow:hidden;';
line += 'width:85px;';
line += 'height:50px;';
line += 'border:none;';
line += '}';
line += '#ac_623317 .ac_container a.ac_image_link .ac_sponsored {';
line += 'display: none;';
line += '}';
line += '#ac_623317 .ac_credit {';
line += 'position: absolute;';
line += 'bottom: 1px;';
line += 'right: 0;';
line += 'font-size: 11px;';
line += 'color: #999;';
line += '}';
line += '#ac_623317 .ac_credit a {';
line += 'display: inline-block;';
line += 'background-color: #707070;';
line += 'opacity: 0.5;';
line += 'padding: 0 5px;';
line += 'margin-left: 2px;';
line += 'border-radius: 15px;';
line += 'font-size: 12px;';
line += 'font-weight: bold;';
line += 'color: #fff;';
line += 'line-height: 17px;';
line += 'text-decoration: none;';
line += '}';
line += '#ac_623317 .ac_disclaimer {';
line += 'font-size: 11px;';
line += '}';
line += '#ac_623317 img.ac_pixel {';
line += 'width:1px!important;';
line += 'height:1px!important;';
line += 'border:none!important;';
line += 'z-index: inherit!important;';
line += 'visibility:visible!important;';
line += 'display:inline!important;';
line += 'background: none!important;';
line += 'background-image:none!important;';
line += 'position:relative!important;';
line += 'margin: 0!important;';
line += 'padding: 0!important;';
line += '}';
line += '/* Modal Styles */';
line += '#ac_623317 .ac_credit_copy,';
line += '#ac_623317 .ac_modal_shading {';
line += 'display: none;';
line += '}';
line += '#ac_623317_modal-overlay {';
line += 'position: fixed;';
line += 'top: 0;';
line += 'left: 0;';
line += 'width: 100%;';
line += 'height: 100%;';
line += 'background-color: rgba(0, 0, 0, 0.75);';
line += 'z-index: 999999;';
line += 'visibility: hidden;';
line += 'opacity: 0;';
line += 'transition: visibility 0s linear 0.25s, opacity 0.25s linear;';
line += '-moz-transition: visibility 0s linear 0.25s, opacity 0.25s linear;';
line += '-webkit-transition: visibility 0s linear 0.25s, opacity 0.25s linear;';
line += '-o-transition: visibility 0s linear 0.25s, opacity 0.25s linear;';
line += '}';
line += '#ac_623317_modal-overlay.hidden {';
line += 'visibility: hidden;';
line += 'opacity: 0;';
line += '}';
line += '#ac_623317_modal-overlay.visible {';
line += 'visibility: visible !important;';
line += 'opacity: 1;';
line += 'transition-delay: 0s;';
line += '}';
line += '#ac_623317_modal-container,';
line += '#ac_623317_modal-container div,';
line += '#ac_623317_modal-container span,';
line += '#ac_623317_modal-container h1,';
line += '#ac_623317_modal-container h2,';
line += '#ac_623317_modal-container h3,';
line += '#ac_623317_modal-container p,';
line += '#ac_623317_modal-container a,';
line += '#ac_623317_modal-container em,';
line += '#ac_623317_modal-container i,';
line += '#ac_623317_modal-container img,';
line += '#ac_623317_modal-container small,';
line += '#ac_623317_modal-container strong,';
line += '#ac_623317_modal-container b,';
line += '#ac_623317_modal-container sub,';
line += '#ac_623317_modal-container sup,';
line += '#ac_623317_modal-container input,';
line += '#ac_623317_modal-container label,';
line += '#ac_623317_modal-container u {';
line += 'margin: 0;';
line += 'padding: 0;';
line += 'border: 0;';
line += 'font-size: 12px;';
line += 'line-height: 1.5em;';
line += 'font: normal 12px/1.5em Arial, Helvetica, sans-serif;';
line += 'vertical-align: baseline;';
line += '}';
line += '#ac_623317_modal-container div,';
line += '#ac_623317_modal-container h1,';
line += '#ac_623317_modal-container h2,';
line += '#ac_623317_modal-container h3,';
line += '#ac_623317_modal-container p {';
line += 'display: block;';
line += '}';
line += '#ac_623317_modal-container span,';
line += '#ac_623317_modal-container a,';
line += '#ac_623317_modal-container em,';
line += '#ac_623317_modal-container i,';
line += '#ac_623317_modal-container img,';
line += '#ac_623317_modal-container small,';
line += '#ac_623317_modal-container strong,';
line += '#ac_623317_modal-container b,';
line += '#ac_623317_modal-container sub,';
line += '#ac_623317_modal-container sup,';
line += '#ac_623317_modal-container input,';
line += '#ac_623317_modal-container label,';
line += '#ac_623317_modal-container u {';
line += 'display: inline;';
line += '}';
line += '#ac_623317_modal-container em,';
line += '#ac_623317_modal-container i {';
line += 'font-style: italic;';
line += '}';
line += '#ac_623317_modal-container h1,';
line += '#ac_623317_modal-container h2,';
line += '#ac_623317_modal-container h3,';
line += '#ac_623317_modal-container strong,';
line += '#ac_623317_modal-container b {';
line += 'font-weight: bold;';
line += '}';
line += '#ac_623317_modal-container {';
line += 'position: fixed;';
line += 'width: 600px;';
line += 'max-width: 100%;';
line += 'min-width: 280px;';
line += 'height: auto;';
line += 'max-height: 100%;';
line += 'background: #fff;';
line += 'border: 1px solid #ababab;';
line += 'box-shadow: 0 4px 16px rgba(0, 0, 0, 0.2);';
line += 'z-index: 1000000;';
line += 'overflow: auto;';
line += 'top: 50%;';
line += 'left: 50%;';
line += '-webkit-transform: translate(-50%, -50%);';
line += '-ms-transform: translate(-50%, -50%);';
line += 'transform: translate(-50%, -50%);';
line += 'line-height: 1.5em;';
line += 'text-align: left;';
line += 'color: #333;';
line += 'font-size: 12px;';
line += 'background-color: #fff;';
line += 'visibility: hidden;';
line += 'opacity: 0;';
line += 'transition: visibility 0s linear 0.25s, opacity 0.25s linear;';
line += '-moz-transition: visibility 0s linear 0.25s, opacity 0.25s linear;';
line += '-webkit-transition: visibility 0s linear 0.25s, opacity 0.25s linear;';
line += '-o-transition: visibility 0s linear 0.25s, opacity 0.25s linear;';
line += '}';
line += '#ac_623317_modal-container.hidden {';
line += 'visibility: hidden;';
line += 'opacity: 0;';
line += '}';
line += '#ac_623317_modal-container.visible {';
line += 'visibility: visible !important;';
line += 'opacity: 1;';
line += 'transition-delay: 0s;';
line += '}';
line += 'div#ac_623317_modal-content {';
line += 'margin: 24px;';
line += '}';
line += '#ac_623317_modal-container p {';
line += 'margin: 0 0 1em 0;';
line += '}';
line += '#ac_623317_modal-container .family-friendly {';
line += 'border: 1px solid #CCC;';
line += 'background: #EEE;';
line += 'padding: 10px;';
line += 'margin-top: 2em;';
line += '}';
line += '#ac_623317_modal-container .family-friendly > p:first-child strong {';
line += '/* Family Friendly Heading */';
line += 'display: block;';
line += 'font-size: 15px;';
line += 'background: url(https://d32oduq093hvot.cloudfront.net/icons/familyfriendly.png) no-repeat 0 center;';
line += 'padding-left: 27px;';
line += 'margin-bottom: 1em;';
line += 'line-height: 27px;';
line += '}';
line += '#ac_623317_modal-container .family-friendly label {';
line += 'display: block;';
line += 'padding-left: 15px;';
line += 'text-indent: -15px;';
line += 'font-weight: bold;';
line += '}';
line += '#ac_623317_modal-container .family-friendly input[type=checkbox] {';
line += 'appearance: checkbox;';
line += '-webkit-appearance: checkbox;';
line += '-moz-appearance: checkbox;';
line += 'width: 13px;';
line += 'height: 13px;';
line += 'padding: 0;';
line += 'margin:0;';
line += 'vertical-align: middle;';
line += 'position: relative;';
line += 'top: -1px;';
line += '*overflow: hidden;';
line += '}';
line += '#ac_623317_modal-close {';
line += 'position: absolute;';
line += 'cursor: pointer;';
line += 'width: 30px;';
line += 'height: 30px;';
line += 'text-indent: -999em;';
line += 'right: 0;';
line += 'top: 0;';
line += '}';
line += '#ac_623317_modal-close:before,';
line += '#ac_623317_modal-close:after {';
line += 'content: \'\';';
line += 'position: absolute;';
line += 'width: 70%;';
line += 'top: 40%;';
line += 'left: 20%;';
line += 'background: #999;';
line += 'height: 2px;';
line += '}';
line += '#ac_623317_modal-close:before {';
line += '-ms-transform: rotate(45deg); /* IE 9 */';
line += '-webkit-transform: rotate(45deg); /* Chrome, Safari, Opera */';
line += 'transform: rotate(45deg);';
line += '}';
line += '#ac_623317_modal-close:after {';
line += '-ms-transform: rotate(-45deg); /* IE 9 */';
line += '-webkit-transform: rotate(-45deg); /* Chrome, Safari, Opera */';
line += 'transform: rotate(-45deg);';
line += '}';
line += '#ac_623317_modal-close:hover:before,';
line += '#ac_623317_modal-close:hover:after {';
line += 'background: #000;';
line += '}';
line += '#ac_623317_modal-container .ac_credit_logo {';
line += 'width: 46%;';
line += 'max-width: 300px;';
line += 'min-width: 200px;';
line += 'margin: 0 auto 24px;';
line += 'text-align: center;';
line += '}';
line += '#ac_623317_modal-container .ac_credit_logo img {';
line += 'width: 100%;';
line += '}';
line += '#ac_623317_modal-container a {';
line += 'color: #F06924;';
line += 'text-decoration: underline;';
line += '}';
line += '/* End Modal Styles */';
line += '</style>';
return line;
}
/* Modification of jsModal - http://jsmodal.com/ */
var Modal_623317 = function() {
var method = {},
modalOverlay = document.createElement("div"),
modalContainer = document.createElement("div"),
modalContent = document.createElement("div"),
modalClose = document.createElement("a"),
defaultSettings = {};
method.open = function(parameters) {
modalContent.innerHTML = parameters.content;
modalOverlay.className = "visible";
modalContainer.className = "visible";
document.onkeydown = function(e) {
if (e.keyCode === 27) {
method.close()
}
};
if (modalClose) modalClose.onclick = function() {
method.close()
};
if (modalOverlay) modalOverlay.onclick = function() {
method.close()
};
};
method.close = function() {
modalOverlay.className = "hidden";
modalContainer.className = "hidden";
return false;
};
modalContainer.setAttribute("id", "ac_623317_modal-container");
modalContainer.style.visibility = "hidden";
modalContent.setAttribute("id", "ac_623317_modal-content");
modalClose.setAttribute("id", "ac_623317_modal-close")
modalClose.innerHTML = "Close Modal";
modalOverlay.setAttribute("id", "ac_623317_modal-overlay");
modalOverlay.style.visibility = "hidden";
modalContainer.appendChild(modalClose);
modalContainer.appendChild(modalContent);
document.body.appendChild(modalContainer);
document.body.appendChild(modalOverlay);
return method
}();
function initJQuery623317() {
var modalContent = document.querySelector('#ac_623317 .ac_credit_copy').innerHTML;
document.querySelector('#ac_623317 .ac_credit a').onclick = function() { Modal_623317.open({content: modalContent}); return false; }
}

(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','https://www.google-analytics.com/analytics.js','ga_ca');ga_ca('create', 'UA-1499181-43', 'auto', 'cad', {'sampleRate': 0.1});ga_ca('cad.send', 'pageview');function familyFriendlyHandler(wid, cb) {
var cad = new Image(1,1);var cnet = new Image(1,1);var ccom = new Image(1,1);
if (cb !== undefined && cb.checked) {
cad.src = 'https://api.content.ad/family-friendly/enable';
cnet.src = 'https://api.content-ad.net/family-friendly/enable';
ccom.src = 'https://app.content-ad.com/FamilyFriendly/Enable?widgetId=' + wid;
} else {
cad.src = 'https://api.content.ad/family-friendly/disable';
cnet.src = 'https://api.content-ad.net/family-friendly/disable';
ccom.src = 'https://app.content-ad.com/FamilyFriendly/Disable';
}
}widget623317.clk = function(target) {
if (target.href.indexOf('duid') === -1) {target.href+='&duid='+widget623317.readCookie('D_DUID');}
if (target.href.indexOf('dtkn') === -1) {target.href+='&dtkn='+encodeURI(widget623317.readCookie('D_TOKEN'));}
if (target.href.indexOf('chc=true') === -1) {target.href+='&chc=true';}
};
widget623317.mover = function(target) {
if (document.getElementsByClassName) {
var parent = target.className.indexOf('image_link') > -1 ? target.parentElement : target.parentElement.parentElement;
var images = parent.getElementsByTagName('img');
if (images.length > 0 && images[0].width >= 120) {
var overlay = parent.getElementsByClassName('ac_overlay');
if (overlay.length > 0) {overlay[0].style.display = 'block';}
}}
};
widget623317.mout = function(target) {
if (document.getElementsByClassName) {
var parent = target.className.indexOf('image_link') > -1 ? target.parentElement : target.parentElement.parentElement;
var overlay = parent.getElementsByClassName('ac_overlay');
if (overlay.length > 0) {overlay[0].style.display = 'none';}
}
};
